//! Handles the creation of and event from the menu.
//!
//! # Menu Handling
//! Allows for the creation and handling of a menu for the boid simulation.
//! The menu currently gives control over the:
//! - Range
//!     - Protected range
//!     - Visible range
//! - Rule weights
//!     - Separation force
//!     - Cohesion force
//!     - Alignment force
//! - Border
//!     - Turning force
//!     - Border margin
//! - Other
//!     - Minimum speed
//!     - Gravity
//!     - Noise force
//!     - Friction coefficient
//!
//! ## Example
//! ```no-run
//! let mut menu: Menu<MenuID> = setup_menu(&boid_settings);
//! ...
//! if let Some(item) = menu::handle_input(&mut menu...) {
//!     on_menu_change(event, ...);
//! }
//! ```

use crate::boids::{Boid, BoidSettings};
use crate::grid::Grid;
use crate::menu::{Menu, MenuItem};

/// Identifiers for each option in the used menu.
pub enum MenuID {
    ProtectedRange,
    VisibleRange,

    SeperationForce,
    CohesionForce,
    AlignmentForce,

    MinSpeed,

    TurnForce,
    Margin,

    Gravity,
    NoiseForce,
    FrictionCoefficient,
}

/// Updates the respective settings in the `boid_data` or `boid_settings` given
/// the `changed_item` event generated by the menu.
pub fn on_menu_change(
    changed_item: &MenuItem<MenuID>,
    boid_settings: &mut BoidSettings,
    boid_data: &mut Grid<Boid>,
) {
    if let MenuItem::FloatSlider { id, current, .. } = changed_item {
        match id {
            MenuID::ProtectedRange => {
                boid_settings.set_protected_range(*current, boid_data);
            }
            MenuID::VisibleRange => {
                boid_settings.set_visible_range(*current, boid_data);
            }
            MenuID::CohesionForce => {
                boid_settings.set_cohesion_force(*current);
            }
            MenuID::SeperationForce => {
                boid_settings.set_separation_force(*current);
            }
            MenuID::AlignmentForce => {
                boid_settings.set_alignment_force(*current);
            }
            MenuID::MinSpeed => {
                boid_settings.set_min_speed(*current);
            }
            MenuID::TurnForce => {
                boid_settings.set_turn_force(*current);
            }
            MenuID::Margin => {
                boid_settings.set_margin(*current);
            }
            MenuID::Gravity => {
                boid_settings.set_gravity(*current);
            }
            MenuID::NoiseForce => {
                boid_settings.set_noise(*current);
            }
            MenuID::FrictionCoefficient => {
                boid_settings.set_friction(*current, boid_settings.squared_friction);
            }
        }
    }
}

/// Sets up a menu which allows for the changing of the options represented in
/// [`MenuID`].
pub fn setup_menu(boid_settings: &BoidSettings) -> Menu<MenuID> {
    let mut menu = Menu::new();
    menu.add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::ProtectedRange,
            current: boid_settings.protected_range,
            min: 0.0,
            max: 100.0,
            step_size: 0.1,
        },
        "Protected Range",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::VisibleRange,
            current: boid_settings.visible_range,
            min: 1.0,
            max: 100.0,
            step_size: 0.1,
        },
        "Visible Range",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::CohesionForce,
            current: boid_settings.cohesion,
            min: 0.0,
            max: 10.0,
            step_size: 0.01,
        },
        "Cohesion Force",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::SeperationForce,
            current: boid_settings.separation,
            min: 0.0,
            max: 10.0,
            step_size: 0.01,
        },
        "Separation Force",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::AlignmentForce,
            current: boid_settings.alignment,
            min: 0.0,
            max: 10.0,
            step_size: 0.01,
        },
        "Alignment Force",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::MinSpeed,
            current: boid_settings.min_speed,
            min: 0.0,
            max: 10.0,
            step_size: 0.1,
        },
        "Min Speed",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::TurnForce,
            current: boid_settings.turn_force,
            min: 0.0,
            max: 10.0,
            step_size: 0.1,
        },
        "Turning force",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::Margin,
            current: boid_settings.margin,
            min: -100.0,
            max: 100.0,
            step_size: 1.0,
        },
        "Margin",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::Gravity,
            current: boid_settings.gravity,
            min: -5.0,
            max: 5.0,
            step_size: 0.01,
        },
        "Gravity",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::NoiseForce,
            current: boid_settings.noise_force,
            min: 0.0,
            max: 1.0,
            step_size: 0.01,
        },
        "Noise force",
    )
    .add_menu_item(
        MenuItem::FloatSlider {
            id: MenuID::FrictionCoefficient,
            current: boid_settings.friction_coefficient,
            min: 0.0,
            max: 1.0,
            step_size: 0.01,
        },
        "Friction coefficient",
    );
    menu
}
